CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "CheckPoints" (
        "PointId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NULL,
        "LatitudeType" text NOT NULL,
        "Latitude" numeric NOT NULL,
        "LongitudeType" text NOT NULL,
        "Longitude" numeric NOT NULL,
        "Altitude" numeric NOT NULL,
        CONSTRAINT "PK_CheckPoints" PRIMARY KEY ("PointId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "Clients" (
        "ClientId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "BirthDate" timestamp without time zone NOT NULL,
        "PhoneNumber" text NULL,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("ClientId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "Employees" (
        "EmployeeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Position" text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "BirthDate" timestamp without time zone NOT NULL,
        "PhoneNumber" text NULL,
        CONSTRAINT "PK_Employees" PRIMARY KEY ("EmployeeId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "Routes" (
        "RouteId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NULL,
        "LengthInKilometers" numeric NOT NULL,
        "ExpectedDurationInDays" numeric NOT NULL,
        CONSTRAINT "PK_Routes" PRIMARY KEY ("RouteId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "CheckPointToRouteMapping" (
        "RouteId" integer NOT NULL,
        "CheckPointId" integer NOT NULL,
        "PositionInRoute" integer NOT NULL,
        CONSTRAINT "PK_CheckPointToRouteMapping" PRIMARY KEY ("RouteId", "CheckPointId"),
        CONSTRAINT "FK_CheckPointToRouteMapping_CheckPoints_CheckPointId" FOREIGN KEY ("CheckPointId") REFERENCES "CheckPoints" ("PointId") ON DELETE CASCADE,
        CONSTRAINT "FK_CheckPointToRouteMapping_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("RouteId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "RoutePoint" (
        "PointId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "RouteId" integer NOT NULL,
        "PositionInRoute" integer NOT NULL,
        "LatitudeType" text NOT NULL,
        "Latitude" numeric NOT NULL,
        "LongitudeType" text NOT NULL,
        "Longitude" numeric NOT NULL,
        "Altitude" numeric NOT NULL,
        CONSTRAINT "PK_RoutePoint" PRIMARY KEY ("PointId"),
        CONSTRAINT "FK_RoutePoint_Routes_RouteId" FOREIGN KEY ("RouteId") REFERENCES "Routes" ("RouteId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "Trips" (
        "TripId" integer NOT NULL,
        "RouteId" integer NOT NULL,
        "LastPassedPointId" integer NOT NULL,
        "StartTime" timestamp without time zone NOT NULL,
        "FinishTime" timestamp without time zone NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_Trips" PRIMARY KEY ("TripId"),
        CONSTRAINT "FK_Trips_RoutePoint_LastPassedPointId" FOREIGN KEY ("LastPassedPointId") REFERENCES "RoutePoint" ("PointId") ON DELETE CASCADE,
        CONSTRAINT "FK_Trips_Routes_TripId" FOREIGN KEY ("TripId") REFERENCES "Routes" ("RouteId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "ClientsToTrips" (
        "ClientId" integer NOT NULL,
        "TripId" integer NOT NULL,
        CONSTRAINT "PK_ClientsToTrips" PRIMARY KEY ("ClientId", "TripId"),
        CONSTRAINT "FK_ClientsToTrips_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("ClientId") ON DELETE CASCADE,
        CONSTRAINT "FK_ClientsToTrips_Trips_TripId" FOREIGN KEY ("TripId") REFERENCES "Trips" ("TripId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE TABLE "EmployeesToTrips" (
        "EmployeeId" integer NOT NULL,
        "TripId" integer NOT NULL,
        CONSTRAINT "PK_EmployeesToTrips" PRIMARY KEY ("EmployeeId", "TripId"),
        CONSTRAINT "FK_EmployeesToTrips_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId") ON DELETE CASCADE,
        CONSTRAINT "FK_EmployeesToTrips_Trips_TripId" FOREIGN KEY ("TripId") REFERENCES "Trips" ("TripId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE INDEX "IX_CheckPointToRouteMapping_CheckPointId" ON "CheckPointToRouteMapping" ("CheckPointId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE INDEX "IX_ClientsToTrips_TripId" ON "ClientsToTrips" ("TripId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE INDEX "IX_EmployeesToTrips_TripId" ON "EmployeesToTrips" ("TripId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE INDEX "IX_RoutePoint_RouteId" ON "RoutePoint" ("RouteId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    CREATE INDEX "IX_Trips_LastPassedPointId" ON "Trips" ("LastPassedPointId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210128181337_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210128181337_InitialMigration', '5.0.2');
    END IF;
END $$;
COMMIT;

